package com.lekha.travel_planner.service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpStatusCodeException;
import org.springframework.web.client.ResourceAccessException;
import org.springframework.web.client.RestTemplate;

import jakarta.annotation.PostConstruct;

/**
 * Service that integrates with the Groq API to generate AI-powered travel itineraries
 * using Groq's OpenAI-compatible chat completions API.
 */
@Service
public class GroqService {

    private static final Logger logger = LoggerFactory.getLogger(GroqService.class);

    @Value("${groq.api.key}")
    private String apiKey;

    @Value("${groq.api.url}")
    private String apiUrl;

    @Value("${groq.api.model}")
    private String model;

    private final RestTemplate restTemplate = new RestTemplate();

    /**
     * Validates the API key at startup and logs a clear warning if it's missing or placeholder.
     */
    @PostConstruct
    public void validateApiKey() {
        if (apiKey == null || apiKey.isBlank() || apiKey.startsWith("gsk_your")) {
            logger.warn("══════════════════════════════════════════════════════════");
            logger.warn("  ⚠️  GROQ_API_KEY is not configured or is a placeholder!");
            logger.warn("  Set it in .env or as an environment variable.");
            logger.warn("  Get a free key at: https://console.groq.com");
            logger.warn("══════════════════════════════════════════════════════════");
        } else {
            logger.info("Groq API key configured successfully ({}...)", apiKey.substring(0, Math.min(8, apiKey.length())));
        }
    }

    /**
     * Generates a detailed travel itinerary using the Groq API.
     *
     * @param destination the travel destination
     * @param duration    trip duration (e.g., "5 days")
     * @param budget      total budget (e.g., "₹50000")
     * @param interests   comma-separated interests (e.g., "History, Food")
     * @return the generated itinerary text, or an error message on failure
     */
    @SuppressWarnings("unchecked")
    public String generateItinerary(String destination,
                                    String duration,
                                    String budget,
                                    String interests) {
        try {
            String prompt = buildPrompt(destination, duration, budget, interests);
            Map<String, Object> requestBody = buildRequestBody(prompt);
            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(requestBody, createHeaders());

            logger.info("Sending itinerary request to Groq API for: {}", destination);
            logger.debug("Groq request — url: {}, model: {}", apiUrl, model);

            ResponseEntity<Map> responseEntity = restTemplate.postForEntity(apiUrl, entity, Map.class);
            Map<String, Object> response = responseEntity.getBody();

            logger.debug("Received Groq response: {}", response);

            if (response == null) {
                logger.error("Groq API returned null response body");
                return "Groq API returned an empty response.";
            }

            if (response.containsKey("error")) {
                logger.error("Groq API error response: {}", response.get("error"));
                return "Groq API error: " + response.get("error");
            }

            List<Map<String, Object>> choices = (List<Map<String, Object>>) response.get("choices");
            if (choices == null || choices.isEmpty()) {
                logger.warn("Groq API returned no choices");
                return "No itinerary generated by Groq.";
            }

            Map<String, Object> firstChoice = choices.get(0);
            if (firstChoice == null || !firstChoice.containsKey("message")) {
                return "No message content returned by Groq.";
            }

            Map<String, Object> message = (Map<String, Object>) firstChoice.get("message");
            if (message == null || !message.containsKey("content")) {
                return "No content returned by Groq.";
            }

            String content = (String) message.get("content");
            if (content == null || content.isBlank()) {
                return "Groq returned empty itinerary content.";
            }

            logger.info("Itinerary generated successfully for: {} ({} chars)", destination, content.length());
            return content;
        } catch (HttpStatusCodeException e) {
            logger.error("Groq API HTTP error: status={}, body={}", e.getStatusCode(), e.getResponseBodyAsString(), e);
            if (e.getStatusCode().is4xxClientError()) {
                return "Failed to generate itinerary due to API request error. Please check your API key and request parameters.";
            }
            if (e.getStatusCode().is5xxServerError()) {
                return "Groq service is temporarily unavailable. Please try again later.";
            }
            return "Failed to generate itinerary. Please try again.";
        } catch (ResourceAccessException e) {
            logger.error("Groq API network error: {}", e.getMessage(), e);
            return "Unable to connect to Groq API. Please check your network connection.";
        } catch (Exception e) {
            logger.error("Groq API unexpected error", e);
            return "Failed to generate itinerary. Check server logs for details.";
        }
    }

    private HttpHeaders createHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(apiKey);
        return headers;
    }

    private String buildPrompt(String destination,
                               String duration,
                               String budget,
                               String interests) {
        return String.format(
            "You are an expert travel consultant.\n\n" +
            "Generate a highly detailed and realistic travel itinerary.\n\n" +
            "Destination: %s\n" +
            "Duration: %s\n" +
            "Budget: %s\n" +
            "Interests: %s\n\n" +
            "Requirements:\n" +
            "1. Day-wise itinerary with Morning, Afternoon and Evening sections.\n" +
            "2. Suggested accommodation category based on budget.\n" +
            "3. Recommended local transportation options.\n" +
            "4. Top attractions with estimated visit duration.\n" +
            "5. Famous local foods and beverages to try.\n" +
            "6. Approximate budget allocation:\n" +
            "   - Accommodation\n" +
            "   - Food\n" +
            "   - Transportation\n" +
            "   - Activities\n" +
            "7. Weather-aware recommendations if weather information is provided.\n" +
            "8. Travel tips and safety guidelines.\n" +
            "9. Emergency travel information.\n" +
            "10. Output should be well formatted using markdown headings and bullet points.\n" +
            "Return only the itinerary content.",
            destination,
            duration,
            budget,
            interests
        );
    }

    private Map<String, Object> buildRequestBody(String prompt) {
        Map<String, Object> body = new HashMap<>();
        body.put("model", model);

        Map<String, String> systemMessage = new HashMap<>();
        systemMessage.put("role", "system");
        systemMessage.put("content", "You are an expert AI travel planner.");

        Map<String, String> userMessage = new HashMap<>();
        userMessage.put("role", "user");
        userMessage.put("content", prompt);

        body.put("messages", List.of(systemMessage, userMessage));
        body.put("temperature", 0.7);
        body.put("max_tokens", 2500);

        return body;
    }
}
